# Generated by Django 5.2.1 on 2025-05-30 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_points', '0003_remove_collectionpoint_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_points.collectionpoint')),
            ],
        ),
    ]
