# Generated by Django 5.2.1 on 2025-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_points', '0004_alter_pointrequest_user_operatinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatinghour',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
