# Generated by Django 5.2.1 on 2025-06-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_points', '0005_operatinghour_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghour',
            name='collection_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='eco_points.collectionpoint'),
        ),
    ]
