# Generated by Django 5.2.1 on 2025-06-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_points', '0006_alter_operatinghour_collection_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='point_images/')),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='eco_points.collectionpoint')),
            ],
        ),
    ]
