# Generated by Django 5.2.1 on 2025-06-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_points', '0007_pointimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointRequest',
        ),
    ]
