# Generated by Django 5.2.1 on 2025-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_points', '0009_collectionpoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
