# Generated by Django 5.2.1 on 2025-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointreview',
            name='exists',
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='collectiontype',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pointreview',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
